


all:  remote_server_client

#Comando iniciar servidor
#indigo_server indigo_ccd_simulator


remote_server_client: remote_server_client.cpp
	g++ remote_server_client.cpp -o remote_server_client  -lindigo

.PHONY: clean

clean:
	rm remote_server_client
